2025-01-05 22:58:29 - INFO - Cargando datos desde CSV...
2025-01-05 22:58:32 - INFO - Eliminando información de zona horaria del índice...
2025-01-05 22:58:32 - INFO - Datos cargados exitosamente: 251947 filas.
2025-01-05 22:58:32 - INFO - Agregando indicadores técnicos...
2025-01-05 22:58:33 - INFO - Calculando VWAP manualmente...
2025-01-05 22:58:33 - INFO - Indicadores agregados. Filas antes: 251947, después: 251898
2025-01-05 22:58:33 - INFO - Columnas después de agregar indicadores técnicos: ['open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_asset_volume', 'number_of_trades', 'taker_buy_base_asset_volume', 'taker_buy_quote_asset_volume', 'ignore', 'RSI', 'MACD', 'MACDh', 'MACDs', 'SMA_10', 'SMA_50', 'EMA_10', 'EMA_50', 'VWAP_D', 'OBV', 'BBL', 'BBM', 'BBU', 'BBB_20_2.0', 'BBP_20_2.0', 'ATR', 'STOCHk', 'STOCHd', 'CCI', 'VWAP']
2025-01-05 22:58:33 - INFO - Generando target binario...
2025-01-05 22:58:33 - INFO - Distribución de clases (0: Vender, 1: Comprar):
target
0.0    7268
1.0    7219
Name: count, dtype: int64
2025-01-05 22:58:33 - INFO - Dividiendo datos en train y test...
2025-01-05 22:58:33 - INFO - Train: 10140 filas, Test: 4347 filas.
2025-01-05 22:58:33 - INFO - Iniciando optimización de hiperparámetros con Optuna...
2025-01-05 22:58:33 - ERROR - Error en el proceso principal: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/pipeline.py", line 469, in fit
    Xt = self._fit(X, y, routed_params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/pipeline.py", line 386, in _fit
    self._validate_steps()
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/pipeline.py", line 256, in _validate_steps
    raise TypeError(
TypeError: All intermediate steps should be transformers and implement fit and transform or be the string 'passthrough' 'SMOTETomek(random_state=44)' (type <class 'imblearn.combine._smote_tomek.SMOTETomek'>) doesn't

